import {
  createInvestAppLinks,
  type InvestAppConfig,
} from '@global-torque/invest-core/app/config';

let links = createInvestAppLinks({ dashboard: '', static: '' });

export const getInvestAppLinks = () => links;

export let urlHome = links.home;
export let urlSignin = links.signin;
export let urlAuthenticator = links.authenticator;
export let urlSignup = links.signup;
export let urlForgot = links.forgot;
export let urlResetPassword = links.resetPassword;
export let urlCheckEmail = links.checkEmail;
export let urlContactUs = links.contactUs;
export let urlOffers = links.offers;
export let urlHowItWorks = links.howItWorks;
export let urlFaq = links.faq;
export let urlBlog = links.blog;
export let urlTerms = links.terms;
export let urlPrivacy = links.privacy;
export let urlCookie = links.cookie;
export let urlServerError = links.serverError;
export let urlNotifications = links.notifications;
export let urlSettings = links.settings;
export let urlSettingsAccountDetails = links.settingsAccountDetails;
export let urlSettingsMfa = links.settingsMfa;
export let urlSettingsSecurity = links.settingsSecurity;
export let urlSettingsBankAccounts = links.settingsBankAccounts;
export let urlProfileAccreditation = links.profileAccreditation;
export let urlInvestmentTimeline = links.investmentTimeline;
export let urlProfileCryptoWallet = links.profileCryptoWallet;
export let urlProfileWallet = links.profileWallet;
export let urlProfileAccount = links.profileAccount;
export let urlProfileEarn = links.profileEarn;
export let urlEarnOverview = links.earnOverview;
export let urlEarnYourPosition = links.earnYourPosition;
export let urlEarnRisk = links.earnRisk;
export let urlProfileKYC = links.profileKyc;
export let urlProfileWalletOtp = links.profileWalletOtp;
export let urlProfilePortfolio = links.profilePortfolio;
export let urlProfileSummary = links.profileSummary;
export let urlProfile = links.profile;
export let urlCreateProfile = links.createProfile;
export let urlOfferSingle = links.offerSingle;
export let urlBlogSingle = links.blogSingle;
export let urlProfileTabSummary = links.profileTabSummary;
export let urlProfileTabPortfolio = links.profileTabPortfolio;
export let urlProfileTabWallet = links.profileTabWallet;
export let urlProfileTabDistributions = links.profileTabDistributions;
export let urlProfileTabEarn = links.profileTabEarn;

export const configureInvestShellNavigation = (config: InvestAppConfig) => {
  links = createInvestAppLinks({ dashboard: config.urls.dashboard, static: config.urls.static });
  urlHome = links.home;
  urlSignin = links.signin;
  urlAuthenticator = links.authenticator;
  urlSignup = links.signup;
  urlForgot = links.forgot;
  urlResetPassword = links.resetPassword;
  urlCheckEmail = links.checkEmail;
  urlContactUs = links.contactUs;
  urlOffers = links.offers;
  urlHowItWorks = links.howItWorks;
  urlFaq = links.faq;
  urlBlog = links.blog;
  urlTerms = links.terms;
  urlPrivacy = links.privacy;
  urlCookie = links.cookie;
  urlServerError = links.serverError;
  urlNotifications = links.notifications;
  urlSettings = links.settings;
  urlSettingsAccountDetails = links.settingsAccountDetails;
  urlSettingsMfa = links.settingsMfa;
  urlSettingsSecurity = links.settingsSecurity;
  urlSettingsBankAccounts = links.settingsBankAccounts;
  urlProfileAccreditation = links.profileAccreditation;
  urlInvestmentTimeline = links.investmentTimeline;
  urlProfileCryptoWallet = links.profileCryptoWallet;
  urlProfileWallet = links.profileWallet;
  urlProfileAccount = links.profileAccount;
  urlProfileEarn = links.profileEarn;
  urlEarnOverview = links.earnOverview;
  urlEarnYourPosition = links.earnYourPosition;
  urlEarnRisk = links.earnRisk;
  urlProfileKYC = links.profileKyc;
  urlProfileWalletOtp = links.profileWalletOtp;
  urlProfilePortfolio = links.profilePortfolio;
  urlProfileSummary = links.profileSummary;
  urlProfile = links.profile;
  urlCreateProfile = links.createProfile;
  urlOfferSingle = links.offerSingle;
  urlBlogSingle = links.blogSingle;
  urlProfileTabSummary = links.profileTabSummary;
  urlProfileTabPortfolio = links.profileTabPortfolio;
  urlProfileTabWallet = links.profileTabWallet;
  urlProfileTabDistributions = links.profileTabDistributions;
  urlProfileTabEarn = links.profileTabEarn;
};
